(refactor): Typography mixins and utility
kyndryl-design-system/foundation pull request #7
Opened 2023-08-02 13:13 UTC by maulik-thaker1

## Summary

Refactor of utility and mixins for typography

## ADO Story or GitHub Issue Link

https://dev.azure.com/Kyndryl/Shidoka%20-%20Bridge%20Design%20System/_workitems/edit/1201287

2023-08-02 13:53 UTC, peterpham-kyndryl approved these changes
Looks good. It'll be better if we can replace some magic numbers with a descriptive var/const. In this loop @for $i from 1 through 4 for example '4' can be assigned to a descriptive var.

2023-08-02 13:56 UTC, brian-patrick-3 requested changes
1. Any particular reason you didn't put the Body styles in a loop also? Not a big deal just curious.
2. I wonder if you could simplify it even further with a nested loop inside each style for each breakpoint?

2023-08-02 13:56 UTC, brian-patrick-3 commented on src/scss/utility/typography.scss
> +@for $i from 1 through 4 {
Display category only has 3 styles.

2023-08-02 14:43 UTC, maulik-thaker1 commented
> 1. Any particular reason you didn't put the Body styles in a loop also? Not a big deal just curious.
> 2. I wonder if you could simplify it even further with a nested loop inside each style for each breakpoint/media query above small?

1. Yes. I don't know but body style is used inside root.scss file so while optimizing it, it creates error at compile time.  
  
<img width="564" alt="Screenshot 2023-08-02 at 8 10 22 PM" src="https://github.com/kyndryl-design-system/foundation/assets/140634142/12a1ff50-9840-4422-a02e-b2769fc8297a">

2. ok will try to keep even shorter if possible.

2023-08-02 14:47 UTC, maulik-thaker1 commented on src/scss/utility/typography.scss
> +@for $i from 1 through 4 {
Done. corrected

2023-08-02 15:46 UTC, brian-patrick-3 approved these changes

2023-08-02 15:47 UTC, brian-patrick-3 commented
> Yes. I don't know but body style is used inside root.scss file so while optimizing it, it creates error at compile time. any reason why we use @include typography.type-body-02; [here](https://github.com/kyndryl-design-system/foundation/blob/beta/src/scss/root.scss#L61) ?

Strange that it errored, but we include that there so the body tag has the default font styles which are inheritable to the rest of the page/components.

I'm going to merge this so I can add a new type style, UI-05, and you can create a new PR if you want to optimize further.

2023-08-02 15:48 UTC, merged

2023-08-02 15:48 UTC, maulik-thaker1 commented
> > Yes. I don't know but body style is used inside root.scss file so while optimizing it, it creates error at compile time. any reason why we use @include typography.type-body-02; [here](https://github.com/kyndryl-design-system/foundation/blob/beta/src/scss/root.scss#L61) ?
> 
> Strange that it errored, but we include that there so the body tag has the default font styles which are inheritable to the rest of the page/components.
> 
> I'm going to merge this so I can add a new type style, UI-05, and you can create a new PR if you want to optimize further.

sure thanks..!!

2023-08-02 15:56 UTC, frodesigns commented
:tada: This PR is included in version 1.0.0-beta.6 :tada:

The release is available on:
- [npm package (@beta dist-tag)](https://www.npmjs.com/package/@kyndryl-design-system/foundation/v/1.0.0-beta.6)
- [GitHub release](https://github.com/kyndryl-design-system/foundation/releases/tag/v1.0.0-beta.6)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket:

2023-11-13 14:45 UTC, brian-patrick-3 commented
:tada: This PR is included in version 1.0.0 :tada:

The release is available on:
- [npm package (@latest dist-tag)](https://www.npmjs.com/package/@kyndryl-design-system/shidoka-foundation/v/1.0.0)
- [GitHub release](https://github.com/kyndryl-design-system/shidoka-foundation/releases/tag/v1.0.0)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: