Feature/layout
kyndryl-design-system/foundation pull request #8
Opened 2023-08-04 14:09 UTC by dennisdolliver

## Summary

Adds in a Layout section to the foundation with two functional pieces:

- Aspect-ratio
- Object-fit

This is a port of functionality from the marketing kyndryl storybook

2023-08-08 15:00 UTC, brian-patrick-3 requested changes
Looking pretty solid! Just a few minor comments.

2023-08-15 03:28 UTC, dennisdolliver commented on src/scss/utility/layout.scss
> +.kd-layout--aspect-ratio {
Addressed in the latest commits

2023-08-15 03:28 UTC, dennisdolliver commented on src/stories/Layout.mdx
> +Work in progress
Addressed in the latest commits

2023-08-15 03:28 UTC, dennisdolliver commented on src/stories/Layout.stories.js
> +            width: 500px;
Addressed in the latest commits

2023-08-15 13:58 UTC, brian-patrick-3 approved these changes

2023-08-15 15:31 UTC, merged

2023-08-15 15:39 UTC, frodesigns commented
:tada: This PR is included in version 1.0.0-beta.11 :tada:

The release is available on:
- [npm package (@beta dist-tag)](https://www.npmjs.com/package/@kyndryl-design-system/foundation/v/1.0.0-beta.11)
- [GitHub release](https://github.com/kyndryl-design-system/foundation/releases/tag/v1.0.0-beta.11)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: